import "../styles/globals.css"
import Head from "next/head"
import Header from "../components/Header"
import Footer from "../components/Footer"
import Navigation from "../components/Navigation"

function MyApp({ Component, pageProps }) {
    return (
        <div className="dark:bg-gray-800 md:h-screen">
            <Head>
                <title>Ibrahim Ghasia</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <Header /> */}
            <Navigation />
            <Component {...pageProps} />
            <Footer />
        </div>
    )
}

export default MyApp
